version: '3'
services:
    nginx:
        image: nginx:latest
        volumes:
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./www:/var/www/html"
        ports:
            - "80:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        restart: always
        depends_on:
            - php
    php:
        build: .
        restart: always
        volumes:
            - "./php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./www:/var/www/html"
        ports:
            - "9000:9000"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://nginx/ | grep -iq "works" || exit 1"]
            interval: 60s
            retries: 5
            start_period: 20s
            timeout: 10s